name: /home/u24sf51014/conda-envs/sro-proof-gpu
channels:
  - defaults
dependencies:
  - anaconda/pkgs/main/linux-64::_libgcc_mutex==0.1=main
  - anaconda/pkgs/main/linux-64::blas==1.0=mkl
  - ca-certificates==2025.11.12
  - nvidia/label/cuda-11.8.0/linux-64::cuda-cccl==11.8.89=0
  - nvidia/label/cuda-11.8.0/linux-64::cuda-cudart==11.8.89=0
  - nvidia/label/cuda-11.8.0/linux-64::cuda-cuobjdump==11.8.86=0
  - nvidia/label/cuda-11.8.0/linux-64::cuda-cupti==11.8.87=0
  - nvidia/label/cuda-11.8.0/linux-64::cuda-cuxxfilt==11.8.86=0
  - nvidia/label/cuda-11.8.0/linux-64::cuda-documentation==11.8.86=0
  - nvidia/label/cuda-11.8.0/linux-64::cuda-driver-dev==11.8.89=0
  - nvidia/label/cuda-11.8.0/linux-64::cuda-gdb==11.8.86=0
  - nvidia/label/cuda-11.8.0/linux-64::cuda-memcheck==11.8.86=0
  - nvidia/label/cuda-11.8.0/linux-64::cuda-nsight==11.8.86=0
  - nvidia/label/cuda-11.8.0/linux-64::cuda-nvcc==11.8.89=0
  - nvidia/label/cuda-11.8.0/linux-64::cuda-nvdisasm==11.8.86=0
  - nvidia/label/cuda-11.8.0/linux-64::cuda-nvml-dev==11.8.86=0
  - nvidia/label/cuda-11.8.0/linux-64::cuda-nvprof==11.8.87=0
  - nvidia/label/cuda-11.8.0/linux-64::cuda-nvprune==11.8.86=0
  - nvidia/label/cuda-11.8.0/linux-64::cuda-nvrtc==11.8.89=0
  - nvidia/label/cuda-11.8.0/linux-64::cuda-nvtx==11.8.86=0
  - nvidia/label/cuda-11.8.0/linux-64::cuda-profiler-api==11.8.86=0
  - nvidia/label/cuda-11.8.0/linux-64::cuda-sanitizer-api==11.8.86=0
  - anaconda/pkgs/main/linux-64::ld_impl_linux-64==2.38=h1181459_1
  - nvidia/label/cuda-11.8.0/linux-64::libcublas==11.11.3.6=0
  - nvidia/label/cuda-11.8.0/linux-64::libcufft==10.9.0.58=0
  - nvidia/label/cuda-11.8.0/linux-64::libcufile==1.4.0.31=0
  - nvidia/label/cuda-11.8.0/linux-64::libcurand==10.3.0.86=0
  - nvidia/label/cuda-11.8.0/linux-64::libcusolver==11.4.1.48=0
  - nvidia/label/cuda-11.8.0/linux-64::libcusparse==11.7.5.86=0
  - nvidia/label/cuda-11.8.0/linux-64::libnpp==11.8.0.86=0
  - nvidia/label/cuda-11.8.0/linux-64::libnvjpeg==11.9.0.86=0
  - anaconda/pkgs/main/linux-64::libstdcxx-ng==11.2.0=h1234567_1
  - nvidia/label/cuda-11.8.0/linux-64::nsight-compute==2022.3.0.22=0
  - anaconda/cloud/pytorch/noarch::pytorch-mutex==1.0=cuda
  - anaconda/pkgs/main/noarch::tzdata==2023c=h04d1e81_0
  - nvidia/label/cuda-11.8.0/linux-64::cuda-command-line-tools==11.8.0=0
  - nvidia/label/cuda-11.8.0/linux-64::cuda-compiler==11.8.0=0
  - nvidia/label/cuda-11.8.0/linux-64::cuda-cudart-dev==11.8.89=0
  - nvidia/label/cuda-11.8.0/linux-64::cuda-libraries==11.8.0=0
  - nvidia/label/cuda-11.8.0/linux-64::cuda-nsight-compute==11.8.0=0
  - nvidia/label/cuda-11.8.0/linux-64::cuda-nvrtc-dev==11.8.89=0
  - nvidia/label/cuda-11.8.0/linux-64::cuda-nvvp==11.8.87=0
  - nvidia/label/cuda-11.8.0/linux-64::gds-tools==1.4.0.31=0
  - nvidia/label/cuda-11.8.0/linux-64::libcublas-dev==11.11.3.6=0
  - nvidia/label/cuda-11.8.0/linux-64::libcufft-dev==10.9.0.58=0
  - nvidia/label/cuda-11.8.0/linux-64::libcufile-dev==1.4.0.31=0
  - nvidia/label/cuda-11.8.0/linux-64::libcurand-dev==10.3.0.86=0
  - nvidia/label/cuda-11.8.0/linux-64::libcusolver-dev==11.4.1.48=0
  - nvidia/label/cuda-11.8.0/linux-64::libcusparse-dev==11.7.5.86=0
  - anaconda/pkgs/main/linux-64::libgomp==11.2.0=h1234567_1
  - nvidia/label/cuda-11.8.0/linux-64::libnpp-dev==11.8.0.86=0
  - nvidia/label/cuda-11.8.0/linux-64::libnvjpeg-dev==11.9.0.86=0
  - anaconda/pkgs/main/linux-64::_openmp_mutex==5.1=1_gnu
  - nvidia/label/cuda-11.8.0/linux-64::cuda-libraries-dev==11.8.0=0
  - nvidia/linux-64::cuda-runtime==11.8.0=0
  - nvidia/label/cuda-11.8.0/linux-64::cuda-visual-tools==11.8.0=0
  - anaconda/pkgs/main/linux-64::libgcc-ng==11.2.0=h1234567_1
  - anaconda/cloud/pytorch/linux-64::pytorch-cuda==11.8=h7e8668a_5
  - anaconda/pkgs/main/linux-64::bzip2==1.0.8=h7b6447c_0
  - nvidia/label/cuda-11.8.0/linux-64::cuda-tools==11.8.0=0
  - anaconda/pkgs/main/linux-64::giflib==5.2.1=h5eee18b_3
  - anaconda/pkgs/main/linux-64::gmp==6.2.1=h295c915_3
  - anaconda/pkgs/main/linux-64::jpeg==9e=h5eee18b_1
  - anaconda/pkgs/main/linux-64::lame==3.100=h7b6447c_0
  - anaconda/pkgs/main/linux-64::lerc==3.0=h295c915_0
  - anaconda/pkgs/main/linux-64::libdeflate==1.17=h5eee18b_1
  - anaconda/pkgs/main/linux-64::libffi==3.4.4=h6a678d5_0
  - anaconda/pkgs/main/linux-64::libiconv==1.16=h7f8727e_2
  - anaconda/cloud/pytorch/linux-64::libjpeg-turbo==2.0.0=h9bf148f_0
  - anaconda/pkgs/main/linux-64::libsodium==1.0.18=h7b6447c_0
  - anaconda/pkgs/main/linux-64::libtasn1==4.19.0=h5eee18b_0
  - anaconda/pkgs/main/linux-64::libunistring==0.9.10=h27cfd23_0
  - anaconda/pkgs/main/linux-64::libuuid==1.41.5=h5eee18b_0
  - anaconda/pkgs/main/linux-64::libwebp-base==1.3.2=h5eee18b_0
  - anaconda/pkgs/main/linux-64::lz4-c==1.9.4=h6a678d5_0
  - anaconda/pkgs/main/linux-64::ncurses==6.4=h6a678d5_0
  - anaconda/pkgs/main/linux-64::openh264==2.1.1=h4ff587b_0
  - openssl==3.0.18
  - anaconda/pkgs/main/linux-64::tbb==2021.8.0=hdb19cb5_0
  - anaconda/pkgs/main/linux-64::xz==5.4.5=h5eee18b_0
  - anaconda/pkgs/main/linux-64::yaml==0.2.5=h7b6447c_0
  - anaconda/pkgs/main/linux-64::zlib==1.2.13=h5eee18b_0
  - nvidia/label/cuda-11.8.0/linux-64::cuda-toolkit==11.8.0=0
  - anaconda/pkgs/main/linux-64::intel-openmp==2023.1.0=hdb19cb5_46306
  - anaconda/pkgs/main/linux-64::libidn2==2.3.4=h5eee18b_0
  - anaconda/pkgs/main/linux-64::libpng==1.6.39=h5eee18b_0
  - anaconda/pkgs/main/linux-64::llvm-openmp==14.0.6=h9e868ea_0
  - anaconda/pkgs/main/linux-64::mpfr==4.0.2=hb69a4c5_1
  - anaconda/pkgs/main/linux-64::nettle==3.7.3=hbbd107a_1
  - anaconda/pkgs/main/linux-64::readline==8.2=h5eee18b_0
  - anaconda/pkgs/main/linux-64::tk==8.6.12=h1ccaba5_0
  - anaconda/pkgs/main/linux-64::zeromq==4.3.4=h2531618_0
  - anaconda/pkgs/main/linux-64::zstd==1.5.5=hc292b87_0
  - anaconda/pkgs/main/linux-64::freetype==2.12.1=h4a9f257_0
  - anaconda/pkgs/main/linux-64::gnutls==3.6.15=he1e5248_0
  - anaconda/pkgs/main/linux-64::libtiff==4.5.1=h6a678d5_0
  - anaconda/pkgs/main/linux-64::mkl==2023.1.0=h213fc3f_46344
  - anaconda/pkgs/main/linux-64::mpc==1.1.0=h10f8cd9_1
  - anaconda/pkgs/main/linux-64::sqlite==3.41.2=h5eee18b_0
  - anaconda/cloud/pytorch/linux-64::ffmpeg==4.3=hf484d3e_0
  - anaconda/pkgs/main/linux-64::lcms2==2.12=h3be6417_0
  - anaconda/pkgs/main/linux-64::libwebp==1.3.2=h11a3e52_0
  - anaconda/pkgs/main/linux-64::openjpeg==2.4.0=h3ad879b_0
  - anaconda/pkgs/main/linux-64::python==3.11.5=h955ad1f_0
  - anaconda/pkgs/main/noarch::backcall==0.2.0=pyhd3eb1b0_0
  - anaconda/pkgs/main/linux-64::brotli-python==1.0.9=py311h6a678d5_7
  - certifi==2025.11.12
  - anaconda/pkgs/main/noarch::charset-normalizer==2.0.4=pyhd3eb1b0_0
  - anaconda/pkgs/main/linux-64::debugpy==1.6.7=py311h6a678d5_0
  - anaconda/pkgs/main/noarch::decorator==5.1.1=pyhd3eb1b0_0
  - anaconda/pkgs/main/noarch::executing==0.8.3=pyhd3eb1b0_0
  - anaconda/pkgs/main/linux-64::filelock==3.13.1=py311h06a4308_0
  - anaconda/pkgs/main/linux-64::gmpy2==2.1.2=py311hc9b5ff0_0
  - anaconda/pkgs/main/linux-64::idna==3.4=py311h06a4308_0
  - anaconda/pkgs/main/linux-64::markupsafe==2.1.1=py311h5eee18b_0
  - anaconda/pkgs/main/linux-64::mkl-service==2.4.0=py311h5eee18b_1
  - anaconda/pkgs/main/linux-64::mpmath==1.3.0=py311h06a4308_0
  - anaconda/pkgs/main/linux-64::nest-asyncio==1.5.6=py311h06a4308_0
  - anaconda/pkgs/main/linux-64::networkx==3.1=py311h06a4308_0
  - anaconda/pkgs/main/linux-64::packaging==23.1=py311h06a4308_0
  - anaconda/pkgs/main/noarch::parso==0.8.3=pyhd3eb1b0_0
  - anaconda/pkgs/main/noarch::pickleshare==0.7.5=pyhd3eb1b0_1003
  - anaconda/pkgs/main/linux-64::pillow==10.0.1=py311ha6cbd5a_0
  - anaconda/pkgs/main/linux-64::platformdirs==3.10.0=py311h06a4308_0
  - anaconda/pkgs/main/linux-64::psutil==5.9.0=py311h5eee18b_0
  - anaconda/pkgs/main/noarch::ptyprocess==0.7.0=pyhd3eb1b0_2
  - anaconda/pkgs/main/noarch::pure_eval==0.2.2=pyhd3eb1b0_0
  - anaconda/pkgs/main/noarch::pycparser==2.21=pyhd3eb1b0_0
  - anaconda/pkgs/main/linux-64::pygments==2.15.1=py311h06a4308_1
  - anaconda/pkgs/main/linux-64::pysocks==1.7.1=py311h06a4308_0
  - anaconda/pkgs/main/linux-64::pyyaml==6.0.1=py311h5eee18b_0
  - anaconda/pkgs/main/linux-64::pyzmq==25.1.0=py311h6a678d5_0
  - anaconda/pkgs/main/linux-64::setuptools==68.2.2=py311h06a4308_0
  - anaconda/pkgs/main/noarch::six==1.16.0=pyhd3eb1b0_1
  - anaconda/pkgs/main/linux-64::tornado==6.3.3=py311h5eee18b_0
  - anaconda/pkgs/main/linux-64::traitlets==5.7.1=py311h06a4308_0
  - anaconda/pkgs/main/linux-64::typing_extensions==4.7.1=py311h06a4308_0
  - anaconda/pkgs/main/noarch::wcwidth==0.2.5=pyhd3eb1b0_0
  - anaconda/pkgs/main/linux-64::wheel==0.41.2=py311h06a4308_0
  - anaconda/pkgs/main/noarch::asttokens==2.0.5=pyhd3eb1b0_0
  - anaconda/pkgs/main/linux-64::cffi==1.16.0=py311h5eee18b_0
  - anaconda/pkgs/main/linux-64::comm==0.1.2=py311h06a4308_0
  - anaconda/pkgs/main/linux-64::jedi==0.18.1=py311h06a4308_1
  - anaconda/pkgs/main/linux-64::jinja2==3.1.2=py311h06a4308_0
  - anaconda/pkgs/main/linux-64::jupyter_core==5.5.0=py311h06a4308_0
  - anaconda/pkgs/main/linux-64::matplotlib-inline==0.1.6=py311h06a4308_0
  - anaconda/pkgs/main/linux-64::numpy-base==1.26.2=py311hf175353_0
  - anaconda/pkgs/main/noarch::pexpect==4.8.0=pyhd3eb1b0_3
  - anaconda/pkgs/main/linux-64::pip==23.3.1=py311h06a4308_0
  - anaconda/pkgs/main/linux-64::prompt-toolkit==3.0.36=py311h06a4308_0
  - anaconda/pkgs/main/noarch::python-dateutil==2.8.2=pyhd3eb1b0_0
  - anaconda/pkgs/main/linux-64::sympy==1.12=py311h06a4308_0
  - anaconda/pkgs/main/linux-64::cryptography==41.0.7=py311hdda0065_0
  - anaconda/pkgs/main/linux-64::jupyter_client==8.6.0=py311h06a4308_0
  - anaconda/pkgs/main/noarch::stack_data==0.2.0=pyhd3eb1b0_0
  - anaconda/pkgs/main/linux-64::ipython==8.15.0=py311h06a4308_0
  - anaconda/pkgs/main/linux-64::pyopenssl==23.2.0=py311h06a4308_0
  - anaconda/pkgs/main/linux-64::ipykernel==6.25.0=py311h92b7b1e_0
  - anaconda/pkgs/main/linux-64::urllib3==1.26.18=py311h06a4308_0
  - anaconda/pkgs/main/linux-64::requests==2.31.0=py311h06a4308_0
  - anaconda/cloud/pytorch/linux-64::pytorch==2.1.1=py3.11_cuda11.8_cudnn8.7.0_0
  - anaconda/cloud/pytorch/linux-64::torchtriton==2.1.0=py311
  - anaconda/cloud/pytorch/linux-64::torchaudio==2.1.1=py311_cu118
  - anaconda/cloud/pytorch/linux-64::torchvision==0.16.1=py311_cu118
  - anaconda/pkgs/main/linux-64::mkl_fft==1.3.8=py311h5eee18b_0
  - anaconda/pkgs/main/linux-64::mkl_random==1.2.4=py311hdb19cb5_0
  - numpy
  - datasets
  - jsonschema
  - pandas
  - pyarrow
  - pydantic
  - rapidfuzz
  - regex
  - tqdm
prefix: /home/u24sf51014/conda-envs/sro-proof-gpu
