name: sro-proof-gpu
channels:
  - conda-forge
  - defaults
  - nvidia
  - pytorch
dependencies:
  - _openmp_mutex=4.5
  - _python_abi3_support=1.0
  - aiohappyeyeballs=2.6.1
  - aiohttp=3.13.3
  - aiosignal=1.4.0
  - alsa-lib=1.2.15.3
  - annotated-doc=0.0.4
  - annotated-types=0.7.0
  - anyio=4.12.1
  - aom=3.9.1
  - attr=2.5.2
  - attrs=25.4.0
  - aws-c-auth=0.9.3
  - aws-c-cal=0.9.13
  - aws-c-common=0.12.6
  - aws-c-compression=0.3.1
  - aws-c-event-stream=0.5.7
  - aws-c-http=0.10.7
  - aws-c-io=0.23.3
  - aws-c-mqtt=0.13.3
  - aws-c-s3=0.11.3
  - aws-c-sdkutils=0.2.4
  - aws-checksums=0.2.7
  - aws-crt-cpp=0.35.4
  - aws-sdk-cpp=1.11.606
  - azure-core-cpp=1.16.2
  - azure-identity-cpp=1.13.3
  - azure-storage-blobs-cpp=12.16.0
  - azure-storage-common-cpp=12.12.0
  - azure-storage-files-datalake-cpp=12.14.0
  - backports.zstd=1.3.0
  - blas=1.0
  - bottleneck=1.4.2
  - brotli-python=1.2.0
  - bzip2=1.0.8
  - c-ares=1.34.6
  - ca-certificates=2026.1.4
  - cairo=1.18.4
  - certifi=2026.1.4
  - charset-normalizer=3.4.4
  - click=8.3.1
  - cpython=3.11.14
  - cuda-cudart=11.8.89
  - cuda-cupti=11.8.87
  - cuda-libraries=11.8.0
  - cuda-nvrtc=11.8.89
  - cuda-nvtx=11.8.86
  - cuda-runtime=11.8.0
  - cuda-version=13.1
  - datasets=4.5.0
  - dav1d=1.2.1
  - dbus=1.16.2
  - dill=0.4.0
  - exceptiongroup=1.3.1
  - ffmpeg=8.0.1
  - filelock=3.24.2
  - font-ttf-dejavu-sans-mono=2.37
  - font-ttf-inconsolata=3.000
  - font-ttf-source-code-pro=2.038
  - font-ttf-ubuntu=0.83
  - fontconfig=2.15.0
  - fonts-conda-ecosystem=1
  - fonts-conda-forge=1
  - freetype=2.14.1
  - fribidi=1.0.16
  - frozenlist=1.7.0
  - fsspec=2025.10.0
  - gdk-pixbuf=2.44.5
  - gflags=2.2.2
  - glog=0.7.1
  - glslang=16.2.0
  - gmp=6.3.0
  - gmpy2=2.2.1
  - graphite2=1.3.14
  - h11=0.16.0
  - h2=4.3.0
  - harfbuzz=12.3.2
  - hf-xet=1.2.1
  - hpack=4.1.0
  - httpcore=1.0.9
  - httpx=0.28.1
  - huggingface_hub=1.4.1
  - hyperframe=6.1.0
  - icu=78.2
  - idna=3.11
  - intel-gmmlib=22.9.0
  - intel-media-driver=25.3.4
  - intel-openmp=2021.4.0
  - jinja2=3.1.6
  - jsonschema=4.26.0
  - jsonschema-specifications=2025.9.1
  - keyutils=1.6.3
  - krb5=1.22.2
  - lame=3.100
  - lcms2=2.18
  - ld_impl_linux-64=2.45.1
  - lerc=4.0.0
  - level-zero=1.28.0
  - libabseil=20260107.1
  - libarrow=23.0.0
  - libarrow-acero=23.0.0
  - libarrow-compute=23.0.0
  - libarrow-dataset=23.0.0
  - libarrow-substrait=23.0.0
  - libass=0.17.4
  - libbrotlicommon=1.2.0
  - libbrotlidec=1.2.0
  - libbrotlienc=1.2.0
  - libcap=2.77
  - libcrc32c=1.1.2
  - libcublas=11.11.3.6
  - libcufft=10.9.0.58
  - libcufile=1.16.1.26
  - libcurand=10.4.1.81
  - libcurl=8.18.0
  - libcusolver=11.4.1.48
  - libcusparse=11.7.5.86
  - libdeflate=1.25
  - libdrm=2.4.125
  - libedit=3.1.20250104
  - libegl=1.7.0
  - libev=4.33
  - libevent=2.1.12
  - libexpat=2.7.3
  - libffi=3.5.2
  - libflac=1.5.0
  - libfreetype=2.14.1
  - libfreetype6=2.14.1
  - libgcc=15.2.0
  - libgcc-ng=15.2.0
  - libgl=1.7.0
  - libglib=2.86.3
  - libglvnd=1.7.0
  - libglx=1.7.0
  - libgomp=15.2.0
  - libgoogle-cloud=2.39.0
  - libgoogle-cloud-storage=2.39.0
  - libgrpc=1.78.0
  - libhwloc=2.12.2
  - libhwy=1.3.0
  - libiconv=1.18
  - libjpeg-turbo=3.1.2
  - libjxl=0.11.2
  - liblzma=5.8.2
  - libnghttp2=1.67.0
  - libnpp=11.8.0.86
  - libnsl=2.0.1
  - libnvjpeg=11.9.0.86
  - libogg=1.3.5
  - libopentelemetry-cpp=1.21.0
  - libopentelemetry-cpp-headers=1.21.0
  - libopenvino=2025.4.1
  - libopenvino-auto-batch-plugin=2025.4.1
  - libopenvino-auto-plugin=2025.4.1
  - libopenvino-hetero-plugin=2025.4.1
  - libopenvino-intel-cpu-plugin=2025.4.1
  - libopenvino-intel-gpu-plugin=2025.4.1
  - libopenvino-intel-npu-plugin=2025.4.1
  - libopenvino-ir-frontend=2025.4.1
  - libopenvino-onnx-frontend=2025.4.1
  - libopenvino-paddle-frontend=2025.4.1
  - libopenvino-pytorch-frontend=2025.4.1
  - libopenvino-tensorflow-frontend=2025.4.1
  - libopenvino-tensorflow-lite-frontend=2025.4.1
  - libopus=1.6.1
  - libparquet=23.0.0
  - libpciaccess=0.18
  - libpng=1.6.55
  - libprotobuf=6.33.5
  - libre2-11=2025.11.05
  - librsvg=2.60.0
  - libsndfile=1.2.2
  - libsqlite=3.51.2
  - libssh2=1.11.1
  - libstdcxx=15.2.0
  - libstdcxx-ng=15.2.0
  - libsystemd0=259.1
  - libthrift=0.22.0
  - libtiff=4.7.1
  - libudev1=259.1
  - libunwind=1.8.3
  - liburing=2.13
  - libusb=1.0.29
  - libutf8proc=2.11.3
  - libuuid=2.41.3
  - libva=2.23.0
  - libvorbis=1.3.7
  - libvpl=2.15.0
  - libvpx=1.15.2
  - libvulkan-loader=1.4.341.0
  - libwebp-base=1.6.0
  - libxcb=1.17.0
  - libxcrypt=4.4.36
  - libxkbcommon=1.13.1
  - libxml2=2.15.1
  - libxml2-16=2.15.1
  - libzlib=1.3.1
  - llvm-openmp=15.0.7
  - lz4-c=1.10.0
  - markdown-it-py=4.0.0
  - markupsafe=3.0.3
  - mdurl=0.1.2
  - mkl=2021.4.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.1
  - mkl_random=1.2.2
  - mpc=1.3.1
  - mpfr=4.2.1
  - mpg123=1.32.9
  - mpmath=1.3.0
  - multidict=6.7.0
  - multiprocess=0.70.18
  - ncurses=6.5
  - networkx=3.4.2
  - nlohmann_json=3.12.0
  - numexpr=2.8.4
  - numpy=1.24.3
  - numpy-base=1.24.3
  - ocl-icd=2.3.3
  - opencl-headers=2025.06.13
  - openh264=2.6.0
  - openjpeg=2.5.4
  - openssl=3.6.1
  - orc=2.2.2
  - packaging=26.0
  - pandas=2.3.3
  - pango=1.56.4
  - pcre2=10.47
  - pillow=12.1.1
  - pip=26.0.1
  - pixman=0.46.4
  - prometheus-cpp=1.3.0
  - propcache=0.3.1
  - pthread-stubs=0.4
  - pugixml=1.15
  - pulseaudio-client=17.0
  - pyarrow=23.0.0
  - pyarrow-core=23.0.0
  - pydantic=2.12.5
  - pydantic-core=2.41.5
  - pygments=2.19.2
  - pysocks=1.7.1
  - python=3.11.14
  - python-dateutil=2.9.0.post0
  - python-gil=3.11.14
  - python-tzdata=2025.3
  - python-xxhash=3.6.0
  - python_abi=3.11
  - pytorch=2.1.1
  - pytorch-cuda=11.8
  - pytorch-mutex=1.0
  - pytz=2025.2
  - pyyaml=6.0.3
  - rapidfuzz=3.14.3
  - re2=2025.11.05
  - readline=8.3
  - referencing=0.37.0
  - regex=2026.1.15
  - requests=2.32.5
  - rich=14.3.2
  - rpds-py=0.30.0
  - s2n=1.6.2
  - sdl2=2.32.56
  - sdl3=3.4.0
  - setuptools=82.0.0
  - shaderc=2025.5
  - shellingham=1.5.4
  - six=1.17.0
  - snappy=1.2.2
  - sniffio=1.3.1
  - spirv-tools=2026.1
  - svt-av1=4.0.1
  - sympy=1.14.0
  - tbb=2022.3.0
  - tk=8.6.13
  - torchaudio=2.1.1
  - torchtriton=2.1.0
  - torchvision=0.16.1
  - tqdm=4.67.3
  - typer=0.23.1
  - typer-slim=0.23.1
  - typing-extensions=4.15.0
  - typing-inspection=0.4.2
  - typing_extensions=4.15.0
  - tzdata=2025c
  - urllib3=2.6.3
  - wayland=1.24.0
  - wayland-protocols=1.47
  - wheel=0.46.3
  - x264=1!164.3095
  - x265=3.5
  - xkeyboard-config=2.46
  - xorg-libice=1.1.2
  - xorg-libsm=1.2.6
  - xorg-libx11=1.8.13
  - xorg-libxau=1.0.12
  - xorg-libxcursor=1.2.3
  - xorg-libxdmcp=1.1.5
  - xorg-libxext=1.3.7
  - xorg-libxfixes=6.0.2
  - xorg-libxi=1.8.2
  - xorg-libxrandr=1.5.5
  - xorg-libxrender=0.9.12
  - xorg-libxscrnsaver=1.2.4
  - xorg-libxtst=1.2.5
  - xxhash=0.8.3
  - yaml=0.2.5
  - yarl=1.22.0
  - zlib=1.3.1
  - zlib-ng=2.3.3
  - zstd=1.5.7
prefix: /home/u24sf51014/.conda/envs/sro-proof-gpu
